
//! Autogenerated weights for `era_v14_custody_governance`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 49.1.0
//! DATE: 2026-09-09, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `era-rpc-03`, CPU: `AMD EPYC-Milan Processor`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// ./target/debug/era-node
// benchmark
// pallet
// --runtime
// target/debug/wbuild/era-runtime/era_runtime.wasm
// --genesis-builder
// none
// --pallet
// era_v14_custody_governance
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --output
// pallets/custody-governance/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

pub trait WeightInfo {
	fn approve_withdrawal() -> Weight;
}

/// Weight functions for `era_v14_custody_governance`.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `FounderCustody::NextRequestId` (r:1 w:1)
	/// Proof: `FounderCustody::NextRequestId` (`max_values`: None, `max_size`: Some(17), added: 2492, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `FounderCustody::PendingWithdrawal` (r:1 w:1)
	/// Proof: `FounderCustody::PendingWithdrawal` (`max_values`: None, `max_size`: Some(66), added: 2541, mode: `MaxEncodedLen`)
	fn approve_withdrawal() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `124`
		//  Estimated: `6196`
		// Minimum execution time: 2_969_459_000 picoseconds.
		Weight::from_parts(3_447_886_000, 0)
			.saturating_add(Weight::from_parts(0, 6196))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(4))
	}
}
