//! Autogenerated candidate weights for `pallet_reward_reserve`.
//!
//! Generated with Substrate Benchmark CLI 49.1.0 on 2026-07-25, using the offline
//! SpecVersion 12 WASM, 8 steps and 5 repeats. The claim component range was 1..=64,
//! matching the runtime election-provider backer bound. All eight dispatchables were measured.

use core::marker::PhantomData;
use frame_support::{traits::Get, weights::Weight};

pub trait WeightInfo {
    fn claim_reward_page(n: u32) -> Weight;
    fn sync_reward_pot() -> Weight;
    fn set_fee_routing_configuration() -> Weight;
    fn spend_ecosystem_treasury() -> Weight;
    fn activate_rewards_and_fee_routing() -> Weight;
    fn retry_deferred_fee_routing() -> Weight;
    fn retry_deferred_author_tip() -> Weight;
    fn cancel_legacy_zero_point_liability() -> Weight;
}

pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
    /// Reads: 16 + n. Writes: 7 + n.
    fn claim_reward_page(n: u32) -> Weight {
        Weight::from_parts(4_341_297_268, 6_196)
            .saturating_add(Weight::from_parts(1_782_078_593, 2_603).saturating_mul(n.into()))
            .saturating_add(T::DbWeight::get().reads(16))
            .saturating_add(T::DbWeight::get().reads(n.into()))
            .saturating_add(T::DbWeight::get().writes(7))
            .saturating_add(T::DbWeight::get().writes(n.into()))
    }

    /// Reads: 3. Writes: 2.
    fn sync_reward_pot() -> Weight {
        Weight::from_parts(509_835_000, 3_593)
            .saturating_add(T::DbWeight::get().reads(3))
            .saturating_add(T::DbWeight::get().writes(2))
    }

    fn set_fee_routing_configuration() -> Weight {
        Weight::from_parts(315_761_000, 1_489)
            .saturating_add(T::DbWeight::get().reads(1))
            .saturating_add(T::DbWeight::get().writes(1))
    }

    fn spend_ecosystem_treasury() -> Weight {
        Weight::from_parts(2_368_704_000, 3_593)
            .saturating_add(T::DbWeight::get().reads(1))
            .saturating_add(T::DbWeight::get().writes(2))
    }

    fn activate_rewards_and_fee_routing() -> Weight {
        Weight::from_parts(3_022_147_000, 8_799)
            .saturating_add(T::DbWeight::get().reads(24))
            .saturating_add(T::DbWeight::get().writes(13))
    }

    fn retry_deferred_fee_routing() -> Weight {
        Weight::from_parts(9_229_156_000, 8_799)
            .saturating_add(T::DbWeight::get().reads(11))
            .saturating_add(T::DbWeight::get().writes(11))
    }

    fn retry_deferred_author_tip() -> Weight {
        Weight::from_parts(3_278_837_000, 6_196)
            .saturating_add(T::DbWeight::get().reads(8))
            .saturating_add(T::DbWeight::get().writes(5))
    }

    fn cancel_legacy_zero_point_liability() -> Weight {
        Weight::from_parts(2_323_909_000, 3_778)
            .saturating_add(T::DbWeight::get().reads(13))
            .saturating_add(T::DbWeight::get().writes(4))
    }
}

impl WeightInfo for () {
    fn claim_reward_page(n: u32) -> Weight {
        Weight::from_parts(4_341_297_268, 6_196)
            .saturating_add(Weight::from_parts(1_782_078_593, 2_603).saturating_mul(n.into()))
    }

    fn sync_reward_pot() -> Weight {
        Weight::from_parts(509_835_000, 3_593)
    }

    fn set_fee_routing_configuration() -> Weight {
        Weight::from_parts(315_761_000, 1_489)
    }

    fn spend_ecosystem_treasury() -> Weight {
        Weight::from_parts(2_368_704_000, 3_593)
    }

    fn activate_rewards_and_fee_routing() -> Weight {
        Weight::from_parts(3_022_147_000, 8_799)
    }

    fn retry_deferred_fee_routing() -> Weight {
        Weight::from_parts(9_229_156_000, 8_799)
    }

    fn retry_deferred_author_tip() -> Weight {
        Weight::from_parts(3_278_837_000, 6_196)
    }

    fn cancel_legacy_zero_point_liability() -> Weight {
        Weight::from_parts(2_323_909_000, 3_778)
    }
}
