
//! Autogenerated weights for `v14_amm_benchmarks`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 49.1.0
//! DATE: 2026-09-20, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `era-rpc-01`, CPU: `AMD EPYC-Milan Processor`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: 1024

// Executed Command:
// ../target/debug/era-node
// benchmark
// pallet
// --chain
// dev
// --pallets
// v14_amm_benchmarks
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --external-repeat
// 2
// --output
// ../nonfinancial-release-20260920/evidence/amm-expanded-weights-5.rs
// --json-file
// ../nonfinancial-release-20260920/evidence/amm-expanded-benchmark-5.json

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `v14_amm_benchmarks`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo<T> {
	/// Storage: `EraV14Amm::Busy` (r:1 w:1)
	/// Proof: `EraV14Amm::Busy` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `Amm::Enabled` (r:1 w:0)
	/// Proof: `Amm::Enabled` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `Amm::ApprovedPairs` (r:1 w:0)
	/// Proof: `Amm::ApprovedPairs` (`max_values`: Some(1024), `max_size`: Some(26), added: 1511, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:1 w:0)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Amm::AdmittedAssets` (r:1 w:0)
	/// Proof: `Amm::AdmittedAssets` (`max_values`: Some(2048), `max_size`: Some(36), added: 1521, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Metadata` (r:1 w:0)
	/// Proof: `Assets::Metadata` (`max_values`: None, `max_size`: Some(170), added: 2645, mode: `MaxEncodedLen`)
	/// Storage: `EraV14Amm::Pools` (r:1 w:1)
	/// Proof: `EraV14Amm::Pools` (`max_values`: Some(1024), `max_size`: Some(186), added: 1671, mode: `MaxEncodedLen`)
	/// Storage: `EraV14Amm::PoolCount` (r:1 w:1)
	/// Proof: `EraV14Amm::PoolCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `EraV14Amm::PoolIndex` (r:1 w:1)
	/// Proof: `EraV14Amm::PoolIndex` (`max_values`: Some(1024), `max_size`: Some(22), added: 1507, mode: `MaxEncodedLen`)
	/// Storage: `EraV14Amm::PoolOrdinal` (r:1 w:1)
	/// Proof: `EraV14Amm::PoolOrdinal` (`max_values`: Some(1024), `max_size`: Some(30), added: 1515, mode: `MaxEncodedLen`)
	/// Storage: `EraV14Amm::Custodies` (r:2 w:1)
	/// Proof: `EraV14Amm::Custodies` (`max_values`: Some(1024), `max_size`: Some(58), added: 1543, mode: `MaxEncodedLen`)
	/// Storage: `EraV14Amm::AccountPools` (r:1 w:0)
	/// Proof: `EraV14Amm::AccountPools` (`max_values`: Some(1048576), `max_size`: Some(690), added: 3165, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Sudo::Key` (r:1 w:0)
	/// Proof: `Sudo::Key` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `Staking::Bonded` (r:1 w:0)
	/// Proof: `Staking::Bonded` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
	/// Storage: `Staking::Ledger` (r:1 w:0)
	/// Proof: `Staking::Ledger` (`max_values`: None, `max_size`: Some(1091), added: 3566, mode: `MaxEncodedLen`)
	/// Storage: `Session::NextKeys` (r:1 w:0)
	/// Proof: `Session::NextKeys` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Proxy::Proxies` (r:1 w:0)
	/// Proof: `Proxy::Proxies` (`max_values`: None, `max_size`: Some(353), added: 2828, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:1 w:0)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	pub fn create_pool() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1795`
		//  Estimated: `6196`
		// Minimum execution time: 2_677_221_000 picoseconds.
		Weight::from_parts(2_709_785_000, 0)
			.saturating_add(Weight::from_parts(0, 6196))
			.saturating_add(T::DbWeight::get().reads(21))
			.saturating_add(T::DbWeight::get().writes(8))
	}
	/// Storage: `EraV14Amm::Busy` (r:1 w:1)
	/// Proof: `EraV14Amm::Busy` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `Amm::Enabled` (r:1 w:0)
	/// Proof: `Amm::Enabled` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `Amm::ApprovedPairs` (r:1 w:0)
	/// Proof: `Amm::ApprovedPairs` (`max_values`: Some(1024), `max_size`: Some(26), added: 1511, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:1 w:1)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Amm::AdmittedAssets` (r:1 w:0)
	/// Proof: `Amm::AdmittedAssets` (`max_values`: Some(2048), `max_size`: Some(36), added: 1521, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Metadata` (r:1 w:0)
	/// Proof: `Assets::Metadata` (`max_values`: None, `max_size`: Some(170), added: 2645, mode: `MaxEncodedLen`)
	/// Storage: `EraV14Amm::Pools` (r:1 w:1)
	/// Proof: `EraV14Amm::Pools` (`max_values`: Some(1024), `max_size`: Some(186), added: 1671, mode: `MaxEncodedLen`)
	/// Storage: `EraV14Amm::Custodies` (r:2 w:0)
	/// Proof: `EraV14Amm::Custodies` (`max_values`: Some(1024), `max_size`: Some(58), added: 1543, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:2 w:2)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `EraV14Amm::Positions` (r:1 w:1)
	/// Proof: `EraV14Amm::Positions` (`max_values`: Some(1048576), `max_size`: Some(90), added: 2565, mode: `MaxEncodedLen`)
	/// Storage: `EraV14Amm::AccountPools` (r:1 w:1)
	/// Proof: `EraV14Amm::AccountPools` (`max_values`: Some(1048576), `max_size`: Some(690), added: 3165, mode: `MaxEncodedLen`)
	/// Storage: `EraV14Amm::Providers` (r:1 w:1)
	/// Proof: `EraV14Amm::Providers` (`max_values`: Some(1024), `max_size`: Some(32796), added: 34281, mode: `MaxEncodedLen`)
	pub fn add_initial() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1238`
		//  Estimated: `35271`
		// Minimum execution time: 5_964_159_000 picoseconds.
		Weight::from_parts(6_046_983_000, 0)
			.saturating_add(Weight::from_parts(0, 35271))
			.saturating_add(T::DbWeight::get().reads(16))
			.saturating_add(T::DbWeight::get().writes(10))
	}
	/// Storage: `EraV14Amm::Busy` (r:1 w:1)
	/// Proof: `EraV14Amm::Busy` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `Amm::Enabled` (r:1 w:0)
	/// Proof: `Amm::Enabled` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `Amm::ApprovedPairs` (r:1 w:0)
	/// Proof: `Amm::ApprovedPairs` (`max_values`: Some(1024), `max_size`: Some(26), added: 1511, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:1 w:1)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Amm::AdmittedAssets` (r:1 w:0)
	/// Proof: `Amm::AdmittedAssets` (`max_values`: Some(2048), `max_size`: Some(36), added: 1521, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Metadata` (r:1 w:0)
	/// Proof: `Assets::Metadata` (`max_values`: None, `max_size`: Some(170), added: 2645, mode: `MaxEncodedLen`)
	/// Storage: `EraV14Amm::Pools` (r:1 w:1)
	/// Proof: `EraV14Amm::Pools` (`max_values`: Some(1024), `max_size`: Some(186), added: 1671, mode: `MaxEncodedLen`)
	/// Storage: `EraV14Amm::Custodies` (r:2 w:0)
	/// Proof: `EraV14Amm::Custodies` (`max_values`: Some(1024), `max_size`: Some(58), added: 1543, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:2 w:2)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `EraV14Amm::Positions` (r:1 w:1)
	/// Proof: `EraV14Amm::Positions` (`max_values`: Some(1048576), `max_size`: Some(90), added: 2565, mode: `MaxEncodedLen`)
	/// Storage: `EraV14Amm::AccountPools` (r:1 w:1)
	/// Proof: `EraV14Amm::AccountPools` (`max_values`: Some(1048576), `max_size`: Some(690), added: 3165, mode: `MaxEncodedLen`)
	/// Storage: `EraV14Amm::Providers` (r:1 w:1)
	/// Proof: `EraV14Amm::Providers` (`max_values`: Some(1024), `max_size`: Some(32796), added: 34281, mode: `MaxEncodedLen`)
	pub fn add_subsequent() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1579`
		//  Estimated: `35271`
		// Minimum execution time: 5_705_704_000 picoseconds.
		Weight::from_parts(5_905_549_000, 0)
			.saturating_add(Weight::from_parts(0, 35271))
			.saturating_add(T::DbWeight::get().reads(16))
			.saturating_add(T::DbWeight::get().writes(10))
	}
	/// Storage: `EraV14Amm::Busy` (r:1 w:1)
	/// Proof: `EraV14Amm::Busy` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `Amm::Enabled` (r:1 w:0)
	/// Proof: `Amm::Enabled` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `Amm::ApprovedPairs` (r:1 w:0)
	/// Proof: `Amm::ApprovedPairs` (`max_values`: Some(1024), `max_size`: Some(26), added: 1511, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:1 w:1)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Amm::AdmittedAssets` (r:1 w:0)
	/// Proof: `Amm::AdmittedAssets` (`max_values`: Some(2048), `max_size`: Some(36), added: 1521, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Metadata` (r:1 w:0)
	/// Proof: `Assets::Metadata` (`max_values`: None, `max_size`: Some(170), added: 2645, mode: `MaxEncodedLen`)
	/// Storage: `EraV14Amm::Pools` (r:1 w:1)
	/// Proof: `EraV14Amm::Pools` (`max_values`: Some(1024), `max_size`: Some(186), added: 1671, mode: `MaxEncodedLen`)
	/// Storage: `EraV14Amm::Custodies` (r:2 w:0)
	/// Proof: `EraV14Amm::Custodies` (`max_values`: Some(1024), `max_size`: Some(58), added: 1543, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:2 w:2)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `EraV14Amm::Positions` (r:1 w:1)
	/// Proof: `EraV14Amm::Positions` (`max_values`: Some(1048576), `max_size`: Some(90), added: 2565, mode: `MaxEncodedLen`)
	/// Storage: `EraV14Amm::AccountPools` (r:1 w:1)
	/// Proof: `EraV14Amm::AccountPools` (`max_values`: Some(1048576), `max_size`: Some(690), added: 3165, mode: `MaxEncodedLen`)
	/// Storage: `EraV14Amm::Providers` (r:1 w:1)
	/// Proof: `EraV14Amm::Providers` (`max_values`: Some(1024), `max_size`: Some(32796), added: 34281, mode: `MaxEncodedLen`)
	pub fn remove_liquidity() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1579`
		//  Estimated: `35271`
		// Minimum execution time: 5_880_584_000 picoseconds.
		Weight::from_parts(6_199_291_000, 0)
			.saturating_add(Weight::from_parts(0, 35271))
			.saturating_add(T::DbWeight::get().reads(16))
			.saturating_add(T::DbWeight::get().writes(10))
	}
	/// Storage: `EraV14Amm::Busy` (r:1 w:1)
	/// Proof: `EraV14Amm::Busy` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `Amm::Enabled` (r:1 w:0)
	/// Proof: `Amm::Enabled` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `Amm::ApprovedPairs` (r:1 w:0)
	/// Proof: `Amm::ApprovedPairs` (`max_values`: Some(1024), `max_size`: Some(26), added: 1511, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:1 w:1)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Amm::AdmittedAssets` (r:1 w:0)
	/// Proof: `Amm::AdmittedAssets` (`max_values`: Some(2048), `max_size`: Some(36), added: 1521, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Metadata` (r:1 w:0)
	/// Proof: `Assets::Metadata` (`max_values`: None, `max_size`: Some(170), added: 2645, mode: `MaxEncodedLen`)
	/// Storage: `EraV14Amm::Pools` (r:1 w:1)
	/// Proof: `EraV14Amm::Pools` (`max_values`: Some(1024), `max_size`: Some(186), added: 1671, mode: `MaxEncodedLen`)
	/// Storage: `EraV14Amm::Custodies` (r:2 w:0)
	/// Proof: `EraV14Amm::Custodies` (`max_values`: Some(1024), `max_size`: Some(58), added: 1543, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:2 w:2)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	pub fn swap_exact_input() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1415`
		//  Estimated: `6208`
		// Minimum execution time: 5_385_403_000 picoseconds.
		Weight::from_parts(5_573_021_000, 0)
			.saturating_add(Weight::from_parts(0, 6208))
			.saturating_add(T::DbWeight::get().reads(13))
			.saturating_add(T::DbWeight::get().writes(7))
	}
	/// Storage: `EraV14Amm::Busy` (r:1 w:1)
	/// Proof: `EraV14Amm::Busy` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `Amm::Enabled` (r:1 w:0)
	/// Proof: `Amm::Enabled` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `Amm::ApprovedPairs` (r:1 w:0)
	/// Proof: `Amm::ApprovedPairs` (`max_values`: Some(1024), `max_size`: Some(26), added: 1511, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:1 w:1)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Amm::AdmittedAssets` (r:1 w:0)
	/// Proof: `Amm::AdmittedAssets` (`max_values`: Some(2048), `max_size`: Some(36), added: 1521, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Metadata` (r:1 w:0)
	/// Proof: `Assets::Metadata` (`max_values`: None, `max_size`: Some(170), added: 2645, mode: `MaxEncodedLen`)
	/// Storage: `EraV14Amm::Pools` (r:1 w:1)
	/// Proof: `EraV14Amm::Pools` (`max_values`: Some(1024), `max_size`: Some(186), added: 1671, mode: `MaxEncodedLen`)
	/// Storage: `EraV14Amm::Custodies` (r:2 w:0)
	/// Proof: `EraV14Amm::Custodies` (`max_values`: Some(1024), `max_size`: Some(58), added: 1543, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:2 w:2)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	pub fn swap_exact_output() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1415`
		//  Estimated: `6208`
		// Minimum execution time: 5_412_100_000 picoseconds.
		Weight::from_parts(5_545_284_000, 0)
			.saturating_add(Weight::from_parts(0, 6208))
			.saturating_add(T::DbWeight::get().reads(13))
			.saturating_add(T::DbWeight::get().writes(7))
	}
	/// Storage: `Amm::ApprovedPairs` (r:1 w:1)
	/// Proof: `Amm::ApprovedPairs` (`max_values`: Some(1024), `max_size`: Some(26), added: 1511, mode: `MaxEncodedLen`)
	/// Storage: `Amm::PairCount` (r:1 w:1)
	/// Proof: `Amm::PairCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:2 w:0)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Amm::AdmittedAssets` (r:0 w:2)
	/// Proof: `Amm::AdmittedAssets` (`max_values`: Some(2048), `max_size`: Some(36), added: 1521, mode: `MaxEncodedLen`)
	pub fn approve_registered() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `701`
		//  Estimated: `6360`
		// Minimum execution time: 508_429_000 picoseconds.
		Weight::from_parts(527_776_000, 0)
			.saturating_add(Weight::from_parts(0, 6360))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: `Amm::Enabled` (r:1 w:1)
	/// Proof: `Amm::Enabled` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `Amm::PairCount` (r:1 w:0)
	/// Proof: `Amm::PairCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	pub fn activate() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `156`
		//  Estimated: `1489`
		// Minimum execution time: 161_862_000 picoseconds.
		Weight::from_parts(168_191_000, 0)
			.saturating_add(Weight::from_parts(0, 1489))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `EraV14Amm::Busy` (r:1 w:1)
	/// Proof: `EraV14Amm::Busy` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `Amm::Enabled` (r:1 w:0)
	/// Proof: `Amm::Enabled` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `Amm::ApprovedPairs` (r:1 w:0)
	/// Proof: `Amm::ApprovedPairs` (`max_values`: Some(1024), `max_size`: Some(26), added: 1511, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:2 w:0)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Amm::AdmittedAssets` (r:2 w:0)
	/// Proof: `Amm::AdmittedAssets` (`max_values`: Some(2048), `max_size`: Some(36), added: 1521, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Metadata` (r:2 w:0)
	/// Proof: `Assets::Metadata` (`max_values`: None, `max_size`: Some(170), added: 2645, mode: `MaxEncodedLen`)
	/// Storage: `EraV14Amm::Pools` (r:1 w:1)
	/// Proof: `EraV14Amm::Pools` (`max_values`: Some(1024), `max_size`: Some(186), added: 1671, mode: `MaxEncodedLen`)
	/// Storage: `EraV14Amm::PoolCount` (r:1 w:1)
	/// Proof: `EraV14Amm::PoolCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `EraV14Amm::PoolIndex` (r:1 w:1)
	/// Proof: `EraV14Amm::PoolIndex` (`max_values`: Some(1024), `max_size`: Some(22), added: 1507, mode: `MaxEncodedLen`)
	/// Storage: `EraV14Amm::PoolOrdinal` (r:1 w:1)
	/// Proof: `EraV14Amm::PoolOrdinal` (`max_values`: Some(1024), `max_size`: Some(30), added: 1515, mode: `MaxEncodedLen`)
	/// Storage: `EraV14Amm::Custodies` (r:2 w:1)
	/// Proof: `EraV14Amm::Custodies` (`max_values`: Some(1024), `max_size`: Some(58), added: 1543, mode: `MaxEncodedLen`)
	/// Storage: `EraV14Amm::AccountPools` (r:1 w:0)
	/// Proof: `EraV14Amm::AccountPools` (`max_values`: Some(1048576), `max_size`: Some(690), added: 3165, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Sudo::Key` (r:1 w:0)
	/// Proof: `Sudo::Key` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `Staking::Bonded` (r:1 w:0)
	/// Proof: `Staking::Bonded` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
	/// Storage: `Staking::Ledger` (r:1 w:0)
	/// Proof: `Staking::Ledger` (`max_values`: None, `max_size`: Some(1091), added: 3566, mode: `MaxEncodedLen`)
	/// Storage: `Session::NextKeys` (r:1 w:0)
	/// Proof: `Session::NextKeys` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Proxy::Proxies` (r:1 w:0)
	/// Proof: `Proxy::Proxies` (`max_values`: None, `max_size`: Some(353), added: 2828, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:2 w:0)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	pub fn create_registered() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2190`
		//  Estimated: `6360`
		// Minimum execution time: 3_447_990_000 picoseconds.
		Weight::from_parts(3_544_173_000, 0)
			.saturating_add(Weight::from_parts(0, 6360))
			.saturating_add(T::DbWeight::get().reads(25))
			.saturating_add(T::DbWeight::get().writes(8))
	}
	/// Storage: `EraV14Amm::Busy` (r:1 w:1)
	/// Proof: `EraV14Amm::Busy` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `Amm::Enabled` (r:1 w:0)
	/// Proof: `Amm::Enabled` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `Amm::ApprovedPairs` (r:1 w:0)
	/// Proof: `Amm::ApprovedPairs` (`max_values`: Some(1024), `max_size`: Some(26), added: 1511, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:2 w:2)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Amm::AdmittedAssets` (r:2 w:0)
	/// Proof: `Amm::AdmittedAssets` (`max_values`: Some(2048), `max_size`: Some(36), added: 1521, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Metadata` (r:2 w:0)
	/// Proof: `Assets::Metadata` (`max_values`: None, `max_size`: Some(170), added: 2645, mode: `MaxEncodedLen`)
	/// Storage: `EraV14Amm::Pools` (r:1 w:1)
	/// Proof: `EraV14Amm::Pools` (`max_values`: Some(1024), `max_size`: Some(186), added: 1671, mode: `MaxEncodedLen`)
	/// Storage: `EraV14Amm::Custodies` (r:2 w:0)
	/// Proof: `EraV14Amm::Custodies` (`max_values`: Some(1024), `max_size`: Some(58), added: 1543, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:4 w:4)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `EraV14Amm::Positions` (r:1 w:1)
	/// Proof: `EraV14Amm::Positions` (`max_values`: Some(1048576), `max_size`: Some(90), added: 2565, mode: `MaxEncodedLen`)
	/// Storage: `EraV14Amm::AccountPools` (r:1 w:1)
	/// Proof: `EraV14Amm::AccountPools` (`max_values`: Some(1048576), `max_size`: Some(690), added: 3165, mode: `MaxEncodedLen`)
	/// Storage: `EraV14Amm::Providers` (r:1 w:1)
	/// Proof: `EraV14Amm::Providers` (`max_values`: Some(1024), `max_size`: Some(32796), added: 34281, mode: `MaxEncodedLen`)
	pub fn add_registered_initial() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1641`
		//  Estimated: `35271`
		// Minimum execution time: 8_499_324_000 picoseconds.
		Weight::from_parts(9_075_726_000, 0)
			.saturating_add(Weight::from_parts(0, 35271))
			.saturating_add(T::DbWeight::get().reads(21))
			.saturating_add(T::DbWeight::get().writes(12))
	}
	/// Storage: `EraV14Amm::Busy` (r:1 w:1)
	/// Proof: `EraV14Amm::Busy` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `Amm::Enabled` (r:1 w:0)
	/// Proof: `Amm::Enabled` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `Amm::ApprovedPairs` (r:1 w:0)
	/// Proof: `Amm::ApprovedPairs` (`max_values`: Some(1024), `max_size`: Some(26), added: 1511, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:1 w:1)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Amm::AdmittedAssets` (r:1 w:0)
	/// Proof: `Amm::AdmittedAssets` (`max_values`: Some(2048), `max_size`: Some(36), added: 1521, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Metadata` (r:1 w:0)
	/// Proof: `Assets::Metadata` (`max_values`: None, `max_size`: Some(170), added: 2645, mode: `MaxEncodedLen`)
	/// Storage: `EraV14Amm::Pools` (r:1 w:1)
	/// Proof: `EraV14Amm::Pools` (`max_values`: Some(1024), `max_size`: Some(186), added: 1671, mode: `MaxEncodedLen`)
	/// Storage: `EraV14Amm::Custodies` (r:2 w:0)
	/// Proof: `EraV14Amm::Custodies` (`max_values`: Some(1024), `max_size`: Some(58), added: 1543, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:2 w:2)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `EraV14Amm::Positions` (r:1 w:1)
	/// Proof: `EraV14Amm::Positions` (`max_values`: Some(1048576), `max_size`: Some(90), added: 2565, mode: `MaxEncodedLen`)
	/// Storage: `EraV14Amm::AccountPools` (r:1 w:1)
	/// Proof: `EraV14Amm::AccountPools` (`max_values`: Some(1048576), `max_size`: Some(690), added: 3165, mode: `MaxEncodedLen`)
	/// Storage: `EraV14Amm::Providers` (r:1 w:1)
	/// Proof: `EraV14Amm::Providers` (`max_values`: Some(1024), `max_size`: Some(32796), added: 34281, mode: `MaxEncodedLen`)
	pub fn add_native_bounded() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `40571`
		//  Estimated: `35271`
		// Minimum execution time: 6_621_043_000 picoseconds.
		Weight::from_parts(6_926_051_000, 0)
			.saturating_add(Weight::from_parts(0, 35271))
			.saturating_add(T::DbWeight::get().reads(16))
			.saturating_add(T::DbWeight::get().writes(10))
	}
	/// Storage: `EraV14Amm::Busy` (r:1 w:1)
	/// Proof: `EraV14Amm::Busy` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `Amm::Enabled` (r:1 w:0)
	/// Proof: `Amm::Enabled` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `Amm::ApprovedPairs` (r:1 w:0)
	/// Proof: `Amm::ApprovedPairs` (`max_values`: Some(1024), `max_size`: Some(26), added: 1511, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:1 w:1)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Amm::AdmittedAssets` (r:1 w:0)
	/// Proof: `Amm::AdmittedAssets` (`max_values`: Some(2048), `max_size`: Some(36), added: 1521, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Metadata` (r:1 w:0)
	/// Proof: `Assets::Metadata` (`max_values`: None, `max_size`: Some(170), added: 2645, mode: `MaxEncodedLen`)
	/// Storage: `EraV14Amm::Pools` (r:1 w:1)
	/// Proof: `EraV14Amm::Pools` (`max_values`: Some(1024), `max_size`: Some(186), added: 1671, mode: `MaxEncodedLen`)
	/// Storage: `EraV14Amm::Custodies` (r:3 w:0)
	/// Proof: `EraV14Amm::Custodies` (`max_values`: Some(1024), `max_size`: Some(58), added: 1543, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:2 w:2)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `EraV14Amm::Positions` (r:1 w:1)
	/// Proof: `EraV14Amm::Positions` (`max_values`: Some(1048576), `max_size`: Some(90), added: 2565, mode: `MaxEncodedLen`)
	/// Storage: `EraV14Amm::AccountPools` (r:1 w:1)
	/// Proof: `EraV14Amm::AccountPools` (`max_values`: Some(1048576), `max_size`: Some(690), added: 3165, mode: `MaxEncodedLen`)
	/// Storage: `EraV14Amm::Providers` (r:1 w:1)
	/// Proof: `EraV14Amm::Providers` (`max_values`: Some(1024), `max_size`: Some(32796), added: 34281, mode: `MaxEncodedLen`)
	pub fn remove_native_bounded() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `40665`
		//  Estimated: `35271`
		// Minimum execution time: 6_647_709_000 picoseconds.
		Weight::from_parts(7_012_009_000, 0)
			.saturating_add(Weight::from_parts(0, 35271))
			.saturating_add(T::DbWeight::get().reads(17))
			.saturating_add(T::DbWeight::get().writes(10))
	}
	/// Storage: `EraV14Amm::Busy` (r:1 w:1)
	/// Proof: `EraV14Amm::Busy` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `Amm::Enabled` (r:1 w:0)
	/// Proof: `Amm::Enabled` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `Amm::ApprovedPairs` (r:1 w:0)
	/// Proof: `Amm::ApprovedPairs` (`max_values`: Some(1024), `max_size`: Some(26), added: 1511, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:1 w:1)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Amm::AdmittedAssets` (r:1 w:0)
	/// Proof: `Amm::AdmittedAssets` (`max_values`: Some(2048), `max_size`: Some(36), added: 1521, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Metadata` (r:1 w:0)
	/// Proof: `Assets::Metadata` (`max_values`: None, `max_size`: Some(170), added: 2645, mode: `MaxEncodedLen`)
	/// Storage: `EraV14Amm::Pools` (r:1 w:1)
	/// Proof: `EraV14Amm::Pools` (`max_values`: Some(1024), `max_size`: Some(186), added: 1671, mode: `MaxEncodedLen`)
	/// Storage: `EraV14Amm::Custodies` (r:2 w:0)
	/// Proof: `EraV14Amm::Custodies` (`max_values`: Some(1024), `max_size`: Some(58), added: 1543, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:2 w:2)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	pub fn swap_native_input_0_0() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1415`
		//  Estimated: `6208`
		// Minimum execution time: 5_440_509_000 picoseconds.
		Weight::from_parts(5_623_230_000, 0)
			.saturating_add(Weight::from_parts(0, 6208))
			.saturating_add(T::DbWeight::get().reads(13))
			.saturating_add(T::DbWeight::get().writes(7))
	}
	/// Storage: `EraV14Amm::Busy` (r:1 w:1)
	/// Proof: `EraV14Amm::Busy` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `Amm::Enabled` (r:1 w:0)
	/// Proof: `Amm::Enabled` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `Amm::ApprovedPairs` (r:1 w:0)
	/// Proof: `Amm::ApprovedPairs` (`max_values`: Some(1024), `max_size`: Some(26), added: 1511, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:1 w:1)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Amm::AdmittedAssets` (r:1 w:0)
	/// Proof: `Amm::AdmittedAssets` (`max_values`: Some(2048), `max_size`: Some(36), added: 1521, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Metadata` (r:1 w:0)
	/// Proof: `Assets::Metadata` (`max_values`: None, `max_size`: Some(170), added: 2645, mode: `MaxEncodedLen`)
	/// Storage: `EraV14Amm::Pools` (r:1 w:1)
	/// Proof: `EraV14Amm::Pools` (`max_values`: Some(1024), `max_size`: Some(186), added: 1671, mode: `MaxEncodedLen`)
	/// Storage: `EraV14Amm::Custodies` (r:3 w:0)
	/// Proof: `EraV14Amm::Custodies` (`max_values`: Some(1024), `max_size`: Some(58), added: 1543, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:3 w:3)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:3 w:2)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	pub fn swap_native_input_0_1() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1518`
		//  Estimated: `8817`
		// Minimum execution time: 5_864_482_000 picoseconds.
		Weight::from_parts(6_062_194_000, 0)
			.saturating_add(Weight::from_parts(0, 8817))
			.saturating_add(T::DbWeight::get().reads(16))
			.saturating_add(T::DbWeight::get().writes(8))
	}
	/// Storage: `EraV14Amm::Busy` (r:1 w:1)
	/// Proof: `EraV14Amm::Busy` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `Amm::Enabled` (r:1 w:0)
	/// Proof: `Amm::Enabled` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `Amm::ApprovedPairs` (r:1 w:0)
	/// Proof: `Amm::ApprovedPairs` (`max_values`: Some(1024), `max_size`: Some(26), added: 1511, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:1 w:1)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Amm::AdmittedAssets` (r:1 w:0)
	/// Proof: `Amm::AdmittedAssets` (`max_values`: Some(2048), `max_size`: Some(36), added: 1521, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Metadata` (r:1 w:0)
	/// Proof: `Assets::Metadata` (`max_values`: None, `max_size`: Some(170), added: 2645, mode: `MaxEncodedLen`)
	/// Storage: `EraV14Amm::Pools` (r:1 w:1)
	/// Proof: `EraV14Amm::Pools` (`max_values`: Some(1024), `max_size`: Some(186), added: 1671, mode: `MaxEncodedLen`)
	/// Storage: `EraV14Amm::Custodies` (r:2 w:0)
	/// Proof: `EraV14Amm::Custodies` (`max_values`: Some(1024), `max_size`: Some(58), added: 1543, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:2 w:2)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	pub fn swap_native_output_0_0() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1415`
		//  Estimated: `6208`
		// Minimum execution time: 5_361_330_000 picoseconds.
		Weight::from_parts(5_574_222_000, 0)
			.saturating_add(Weight::from_parts(0, 6208))
			.saturating_add(T::DbWeight::get().reads(13))
			.saturating_add(T::DbWeight::get().writes(7))
	}
	/// Storage: `EraV14Amm::Busy` (r:1 w:1)
	/// Proof: `EraV14Amm::Busy` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `Amm::Enabled` (r:1 w:0)
	/// Proof: `Amm::Enabled` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `Amm::ApprovedPairs` (r:1 w:0)
	/// Proof: `Amm::ApprovedPairs` (`max_values`: Some(1024), `max_size`: Some(26), added: 1511, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:1 w:1)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Amm::AdmittedAssets` (r:1 w:0)
	/// Proof: `Amm::AdmittedAssets` (`max_values`: Some(2048), `max_size`: Some(36), added: 1521, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Metadata` (r:1 w:0)
	/// Proof: `Assets::Metadata` (`max_values`: None, `max_size`: Some(170), added: 2645, mode: `MaxEncodedLen`)
	/// Storage: `EraV14Amm::Pools` (r:1 w:1)
	/// Proof: `EraV14Amm::Pools` (`max_values`: Some(1024), `max_size`: Some(186), added: 1671, mode: `MaxEncodedLen`)
	/// Storage: `EraV14Amm::Custodies` (r:3 w:0)
	/// Proof: `EraV14Amm::Custodies` (`max_values`: Some(1024), `max_size`: Some(58), added: 1543, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:3 w:3)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:3 w:2)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	pub fn swap_native_output_0_1() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1518`
		//  Estimated: `8817`
		// Minimum execution time: 5_969_685_000 picoseconds.
		Weight::from_parts(6_248_811_000, 0)
			.saturating_add(Weight::from_parts(0, 8817))
			.saturating_add(T::DbWeight::get().reads(16))
			.saturating_add(T::DbWeight::get().writes(8))
	}
	/// Storage: `EraV14Amm::Busy` (r:1 w:1)
	/// Proof: `EraV14Amm::Busy` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `Amm::Enabled` (r:1 w:0)
	/// Proof: `Amm::Enabled` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `Amm::ApprovedPairs` (r:1 w:0)
	/// Proof: `Amm::ApprovedPairs` (`max_values`: Some(1024), `max_size`: Some(26), added: 1511, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:1 w:1)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Amm::AdmittedAssets` (r:1 w:0)
	/// Proof: `Amm::AdmittedAssets` (`max_values`: Some(2048), `max_size`: Some(36), added: 1521, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Metadata` (r:1 w:0)
	/// Proof: `Assets::Metadata` (`max_values`: None, `max_size`: Some(170), added: 2645, mode: `MaxEncodedLen`)
	/// Storage: `EraV14Amm::Pools` (r:1 w:1)
	/// Proof: `EraV14Amm::Pools` (`max_values`: Some(1024), `max_size`: Some(186), added: 1671, mode: `MaxEncodedLen`)
	/// Storage: `EraV14Amm::Custodies` (r:2 w:0)
	/// Proof: `EraV14Amm::Custodies` (`max_values`: Some(1024), `max_size`: Some(58), added: 1543, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:2 w:2)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	pub fn swap_native_input_1_0() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1415`
		//  Estimated: `6208`
		// Minimum execution time: 5_406_662_000 picoseconds.
		Weight::from_parts(5_746_239_000, 0)
			.saturating_add(Weight::from_parts(0, 6208))
			.saturating_add(T::DbWeight::get().reads(13))
			.saturating_add(T::DbWeight::get().writes(7))
	}
	/// Storage: `EraV14Amm::Busy` (r:1 w:1)
	/// Proof: `EraV14Amm::Busy` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `Amm::Enabled` (r:1 w:0)
	/// Proof: `Amm::Enabled` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `Amm::ApprovedPairs` (r:1 w:0)
	/// Proof: `Amm::ApprovedPairs` (`max_values`: Some(1024), `max_size`: Some(26), added: 1511, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:1 w:1)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Amm::AdmittedAssets` (r:1 w:0)
	/// Proof: `Amm::AdmittedAssets` (`max_values`: Some(2048), `max_size`: Some(36), added: 1521, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Metadata` (r:1 w:0)
	/// Proof: `Assets::Metadata` (`max_values`: None, `max_size`: Some(170), added: 2645, mode: `MaxEncodedLen`)
	/// Storage: `EraV14Amm::Pools` (r:1 w:1)
	/// Proof: `EraV14Amm::Pools` (`max_values`: Some(1024), `max_size`: Some(186), added: 1671, mode: `MaxEncodedLen`)
	/// Storage: `EraV14Amm::Custodies` (r:3 w:0)
	/// Proof: `EraV14Amm::Custodies` (`max_values`: Some(1024), `max_size`: Some(58), added: 1543, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:3 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:3 w:2)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	pub fn swap_native_input_1_1() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1518`
		//  Estimated: `8817`
		// Minimum execution time: 5_924_644_000 picoseconds.
		Weight::from_parts(6_295_434_000, 0)
			.saturating_add(Weight::from_parts(0, 8817))
			.saturating_add(T::DbWeight::get().reads(16))
			.saturating_add(T::DbWeight::get().writes(7))
	}
	/// Storage: `EraV14Amm::Busy` (r:1 w:1)
	/// Proof: `EraV14Amm::Busy` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `Amm::Enabled` (r:1 w:0)
	/// Proof: `Amm::Enabled` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `Amm::ApprovedPairs` (r:1 w:0)
	/// Proof: `Amm::ApprovedPairs` (`max_values`: Some(1024), `max_size`: Some(26), added: 1511, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:1 w:1)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Amm::AdmittedAssets` (r:1 w:0)
	/// Proof: `Amm::AdmittedAssets` (`max_values`: Some(2048), `max_size`: Some(36), added: 1521, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Metadata` (r:1 w:0)
	/// Proof: `Assets::Metadata` (`max_values`: None, `max_size`: Some(170), added: 2645, mode: `MaxEncodedLen`)
	/// Storage: `EraV14Amm::Pools` (r:1 w:1)
	/// Proof: `EraV14Amm::Pools` (`max_values`: Some(1024), `max_size`: Some(186), added: 1671, mode: `MaxEncodedLen`)
	/// Storage: `EraV14Amm::Custodies` (r:2 w:0)
	/// Proof: `EraV14Amm::Custodies` (`max_values`: Some(1024), `max_size`: Some(58), added: 1543, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:2 w:2)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	pub fn swap_native_output_1_0() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1415`
		//  Estimated: `6208`
		// Minimum execution time: 5_414_933_000 picoseconds.
		Weight::from_parts(5_783_049_000, 0)
			.saturating_add(Weight::from_parts(0, 6208))
			.saturating_add(T::DbWeight::get().reads(13))
			.saturating_add(T::DbWeight::get().writes(7))
	}
	/// Storage: `EraV14Amm::Busy` (r:1 w:1)
	/// Proof: `EraV14Amm::Busy` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `Amm::Enabled` (r:1 w:0)
	/// Proof: `Amm::Enabled` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `Amm::ApprovedPairs` (r:1 w:0)
	/// Proof: `Amm::ApprovedPairs` (`max_values`: Some(1024), `max_size`: Some(26), added: 1511, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:1 w:1)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Amm::AdmittedAssets` (r:1 w:0)
	/// Proof: `Amm::AdmittedAssets` (`max_values`: Some(2048), `max_size`: Some(36), added: 1521, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Metadata` (r:1 w:0)
	/// Proof: `Assets::Metadata` (`max_values`: None, `max_size`: Some(170), added: 2645, mode: `MaxEncodedLen`)
	/// Storage: `EraV14Amm::Pools` (r:1 w:1)
	/// Proof: `EraV14Amm::Pools` (`max_values`: Some(1024), `max_size`: Some(186), added: 1671, mode: `MaxEncodedLen`)
	/// Storage: `EraV14Amm::Custodies` (r:3 w:0)
	/// Proof: `EraV14Amm::Custodies` (`max_values`: Some(1024), `max_size`: Some(58), added: 1543, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:3 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:3 w:2)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	pub fn swap_native_output_1_1() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1518`
		//  Estimated: `8817`
		// Minimum execution time: 5_834_430_000 picoseconds.
		Weight::from_parts(6_021_748_000, 0)
			.saturating_add(Weight::from_parts(0, 8817))
			.saturating_add(T::DbWeight::get().reads(16))
			.saturating_add(T::DbWeight::get().writes(7))
	}
	/// Storage: `EraV14Amm::Busy` (r:1 w:1)
	/// Proof: `EraV14Amm::Busy` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `Amm::Enabled` (r:1 w:0)
	/// Proof: `Amm::Enabled` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `Amm::ApprovedPairs` (r:1 w:0)
	/// Proof: `Amm::ApprovedPairs` (`max_values`: Some(1024), `max_size`: Some(26), added: 1511, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:2 w:2)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Amm::AdmittedAssets` (r:2 w:0)
	/// Proof: `Amm::AdmittedAssets` (`max_values`: Some(2048), `max_size`: Some(36), added: 1521, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Metadata` (r:2 w:0)
	/// Proof: `Assets::Metadata` (`max_values`: None, `max_size`: Some(170), added: 2645, mode: `MaxEncodedLen`)
	/// Storage: `EraV14Amm::Pools` (r:1 w:1)
	/// Proof: `EraV14Amm::Pools` (`max_values`: Some(1024), `max_size`: Some(186), added: 1671, mode: `MaxEncodedLen`)
	/// Storage: `EraV14Amm::Custodies` (r:2 w:0)
	/// Proof: `EraV14Amm::Custodies` (`max_values`: Some(1024), `max_size`: Some(58), added: 1543, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:0)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:4 w:4)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `EraV14Amm::Positions` (r:1 w:1)
	/// Proof: `EraV14Amm::Positions` (`max_values`: Some(1048576), `max_size`: Some(90), added: 2565, mode: `MaxEncodedLen`)
	/// Storage: `EraV14Amm::AccountPools` (r:1 w:1)
	/// Proof: `EraV14Amm::AccountPools` (`max_values`: Some(1048576), `max_size`: Some(690), added: 3165, mode: `MaxEncodedLen`)
	/// Storage: `EraV14Amm::Providers` (r:1 w:1)
	/// Proof: `EraV14Amm::Providers` (`max_values`: Some(1024), `max_size`: Some(32796), added: 34281, mode: `MaxEncodedLen`)
	pub fn add_registered_bounded() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `41731`
		//  Estimated: `35271`
		// Minimum execution time: 8_993_152_000 picoseconds.
		Weight::from_parts(9_460_345_000, 0)
			.saturating_add(Weight::from_parts(0, 35271))
			.saturating_add(T::DbWeight::get().reads(21))
			.saturating_add(T::DbWeight::get().writes(11))
	}
	/// Storage: `EraV14Amm::Busy` (r:1 w:1)
	/// Proof: `EraV14Amm::Busy` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `Amm::Enabled` (r:1 w:0)
	/// Proof: `Amm::Enabled` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `Amm::ApprovedPairs` (r:1 w:0)
	/// Proof: `Amm::ApprovedPairs` (`max_values`: Some(1024), `max_size`: Some(26), added: 1511, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:2 w:2)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Amm::AdmittedAssets` (r:2 w:0)
	/// Proof: `Amm::AdmittedAssets` (`max_values`: Some(2048), `max_size`: Some(36), added: 1521, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Metadata` (r:2 w:0)
	/// Proof: `Assets::Metadata` (`max_values`: None, `max_size`: Some(170), added: 2645, mode: `MaxEncodedLen`)
	/// Storage: `EraV14Amm::Pools` (r:1 w:1)
	/// Proof: `EraV14Amm::Pools` (`max_values`: Some(1024), `max_size`: Some(186), added: 1671, mode: `MaxEncodedLen`)
	/// Storage: `EraV14Amm::Custodies` (r:3 w:0)
	/// Proof: `EraV14Amm::Custodies` (`max_values`: Some(1024), `max_size`: Some(58), added: 1543, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:4 w:4)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `EraV14Amm::Positions` (r:1 w:1)
	/// Proof: `EraV14Amm::Positions` (`max_values`: Some(1048576), `max_size`: Some(90), added: 2565, mode: `MaxEncodedLen`)
	/// Storage: `EraV14Amm::AccountPools` (r:1 w:1)
	/// Proof: `EraV14Amm::AccountPools` (`max_values`: Some(1048576), `max_size`: Some(690), added: 3165, mode: `MaxEncodedLen`)
	/// Storage: `EraV14Amm::Providers` (r:1 w:1)
	/// Proof: `EraV14Amm::Providers` (`max_values`: Some(1024), `max_size`: Some(32796), added: 34281, mode: `MaxEncodedLen`)
	pub fn remove_registered_bounded() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `41786`
		//  Estimated: `35271`
		// Minimum execution time: 9_232_652_000 picoseconds.
		Weight::from_parts(9_611_412_000, 0)
			.saturating_add(Weight::from_parts(0, 35271))
			.saturating_add(T::DbWeight::get().reads(22))
			.saturating_add(T::DbWeight::get().writes(12))
	}
	/// Storage: `EraV14Amm::Busy` (r:1 w:1)
	/// Proof: `EraV14Amm::Busy` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `Amm::Enabled` (r:1 w:0)
	/// Proof: `Amm::Enabled` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `Amm::ApprovedPairs` (r:1 w:0)
	/// Proof: `Amm::ApprovedPairs` (`max_values`: Some(1024), `max_size`: Some(26), added: 1511, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:2 w:2)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Amm::AdmittedAssets` (r:2 w:0)
	/// Proof: `Amm::AdmittedAssets` (`max_values`: Some(2048), `max_size`: Some(36), added: 1521, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Metadata` (r:2 w:0)
	/// Proof: `Assets::Metadata` (`max_values`: None, `max_size`: Some(170), added: 2645, mode: `MaxEncodedLen`)
	/// Storage: `EraV14Amm::Pools` (r:1 w:1)
	/// Proof: `EraV14Amm::Pools` (`max_values`: Some(1024), `max_size`: Some(186), added: 1671, mode: `MaxEncodedLen`)
	/// Storage: `EraV14Amm::Custodies` (r:2 w:0)
	/// Proof: `EraV14Amm::Custodies` (`max_values`: Some(1024), `max_size`: Some(58), added: 1543, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:0)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:4 w:4)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	pub fn swap_registered_input_0_0() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1894`
		//  Estimated: `11426`
		// Minimum execution time: 7_680_387_000 picoseconds.
		Weight::from_parts(7_966_942_000, 0)
			.saturating_add(Weight::from_parts(0, 11426))
			.saturating_add(T::DbWeight::get().reads(18))
			.saturating_add(T::DbWeight::get().writes(8))
	}
	/// Storage: `EraV14Amm::Busy` (r:1 w:1)
	/// Proof: `EraV14Amm::Busy` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `Amm::Enabled` (r:1 w:0)
	/// Proof: `Amm::Enabled` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `Amm::ApprovedPairs` (r:1 w:0)
	/// Proof: `Amm::ApprovedPairs` (`max_values`: Some(1024), `max_size`: Some(26), added: 1511, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:2 w:2)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Amm::AdmittedAssets` (r:2 w:0)
	/// Proof: `Amm::AdmittedAssets` (`max_values`: Some(2048), `max_size`: Some(36), added: 1521, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Metadata` (r:2 w:0)
	/// Proof: `Assets::Metadata` (`max_values`: None, `max_size`: Some(170), added: 2645, mode: `MaxEncodedLen`)
	/// Storage: `EraV14Amm::Pools` (r:1 w:1)
	/// Proof: `EraV14Amm::Pools` (`max_values`: Some(1024), `max_size`: Some(186), added: 1671, mode: `MaxEncodedLen`)
	/// Storage: `EraV14Amm::Custodies` (r:3 w:0)
	/// Proof: `EraV14Amm::Custodies` (`max_values`: Some(1024), `max_size`: Some(58), added: 1543, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:3 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:6 w:4)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	pub fn swap_registered_input_0_1() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1997`
		//  Estimated: `16644`
		// Minimum execution time: 8_584_040_000 picoseconds.
		Weight::from_parts(8_784_556_000, 0)
			.saturating_add(Weight::from_parts(0, 16644))
			.saturating_add(T::DbWeight::get().reads(22))
			.saturating_add(T::DbWeight::get().writes(9))
	}
	/// Storage: `EraV14Amm::Busy` (r:1 w:1)
	/// Proof: `EraV14Amm::Busy` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `Amm::Enabled` (r:1 w:0)
	/// Proof: `Amm::Enabled` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `Amm::ApprovedPairs` (r:1 w:0)
	/// Proof: `Amm::ApprovedPairs` (`max_values`: Some(1024), `max_size`: Some(26), added: 1511, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:2 w:2)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Amm::AdmittedAssets` (r:2 w:0)
	/// Proof: `Amm::AdmittedAssets` (`max_values`: Some(2048), `max_size`: Some(36), added: 1521, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Metadata` (r:2 w:0)
	/// Proof: `Assets::Metadata` (`max_values`: None, `max_size`: Some(170), added: 2645, mode: `MaxEncodedLen`)
	/// Storage: `EraV14Amm::Pools` (r:1 w:1)
	/// Proof: `EraV14Amm::Pools` (`max_values`: Some(1024), `max_size`: Some(186), added: 1671, mode: `MaxEncodedLen`)
	/// Storage: `EraV14Amm::Custodies` (r:2 w:0)
	/// Proof: `EraV14Amm::Custodies` (`max_values`: Some(1024), `max_size`: Some(58), added: 1543, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:0)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:4 w:4)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	pub fn swap_registered_output_0_0() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1894`
		//  Estimated: `11426`
		// Minimum execution time: 7_697_481_000 picoseconds.
		Weight::from_parts(7_960_403_000, 0)
			.saturating_add(Weight::from_parts(0, 11426))
			.saturating_add(T::DbWeight::get().reads(18))
			.saturating_add(T::DbWeight::get().writes(8))
	}
	/// Storage: `EraV14Amm::Busy` (r:1 w:1)
	/// Proof: `EraV14Amm::Busy` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `Amm::Enabled` (r:1 w:0)
	/// Proof: `Amm::Enabled` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `Amm::ApprovedPairs` (r:1 w:0)
	/// Proof: `Amm::ApprovedPairs` (`max_values`: Some(1024), `max_size`: Some(26), added: 1511, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:2 w:2)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Amm::AdmittedAssets` (r:2 w:0)
	/// Proof: `Amm::AdmittedAssets` (`max_values`: Some(2048), `max_size`: Some(36), added: 1521, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Metadata` (r:2 w:0)
	/// Proof: `Assets::Metadata` (`max_values`: None, `max_size`: Some(170), added: 2645, mode: `MaxEncodedLen`)
	/// Storage: `EraV14Amm::Pools` (r:1 w:1)
	/// Proof: `EraV14Amm::Pools` (`max_values`: Some(1024), `max_size`: Some(186), added: 1671, mode: `MaxEncodedLen`)
	/// Storage: `EraV14Amm::Custodies` (r:3 w:0)
	/// Proof: `EraV14Amm::Custodies` (`max_values`: Some(1024), `max_size`: Some(58), added: 1543, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:3 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:6 w:4)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	pub fn swap_registered_output_0_1() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1997`
		//  Estimated: `16644`
		// Minimum execution time: 8_676_127_000 picoseconds.
		Weight::from_parts(8_984_401_000, 0)
			.saturating_add(Weight::from_parts(0, 16644))
			.saturating_add(T::DbWeight::get().reads(22))
			.saturating_add(T::DbWeight::get().writes(9))
	}
	/// Storage: `EraV14Amm::Busy` (r:1 w:1)
	/// Proof: `EraV14Amm::Busy` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `Amm::Enabled` (r:1 w:0)
	/// Proof: `Amm::Enabled` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `Amm::ApprovedPairs` (r:1 w:0)
	/// Proof: `Amm::ApprovedPairs` (`max_values`: Some(1024), `max_size`: Some(26), added: 1511, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:2 w:2)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Amm::AdmittedAssets` (r:2 w:0)
	/// Proof: `Amm::AdmittedAssets` (`max_values`: Some(2048), `max_size`: Some(36), added: 1521, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Metadata` (r:2 w:0)
	/// Proof: `Assets::Metadata` (`max_values`: None, `max_size`: Some(170), added: 2645, mode: `MaxEncodedLen`)
	/// Storage: `EraV14Amm::Pools` (r:1 w:1)
	/// Proof: `EraV14Amm::Pools` (`max_values`: Some(1024), `max_size`: Some(186), added: 1671, mode: `MaxEncodedLen`)
	/// Storage: `EraV14Amm::Custodies` (r:2 w:0)
	/// Proof: `EraV14Amm::Custodies` (`max_values`: Some(1024), `max_size`: Some(58), added: 1543, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:0)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:4 w:4)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	pub fn swap_registered_input_1_0() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1894`
		//  Estimated: `11426`
		// Minimum execution time: 7_728_033_000 picoseconds.
		Weight::from_parts(7_937_261_000, 0)
			.saturating_add(Weight::from_parts(0, 11426))
			.saturating_add(T::DbWeight::get().reads(18))
			.saturating_add(T::DbWeight::get().writes(8))
	}
	/// Storage: `EraV14Amm::Busy` (r:1 w:1)
	/// Proof: `EraV14Amm::Busy` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `Amm::Enabled` (r:1 w:0)
	/// Proof: `Amm::Enabled` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `Amm::ApprovedPairs` (r:1 w:0)
	/// Proof: `Amm::ApprovedPairs` (`max_values`: Some(1024), `max_size`: Some(26), added: 1511, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:2 w:2)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Amm::AdmittedAssets` (r:2 w:0)
	/// Proof: `Amm::AdmittedAssets` (`max_values`: Some(2048), `max_size`: Some(36), added: 1521, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Metadata` (r:2 w:0)
	/// Proof: `Assets::Metadata` (`max_values`: None, `max_size`: Some(170), added: 2645, mode: `MaxEncodedLen`)
	/// Storage: `EraV14Amm::Pools` (r:1 w:1)
	/// Proof: `EraV14Amm::Pools` (`max_values`: Some(1024), `max_size`: Some(186), added: 1671, mode: `MaxEncodedLen`)
	/// Storage: `EraV14Amm::Custodies` (r:3 w:0)
	/// Proof: `EraV14Amm::Custodies` (`max_values`: Some(1024), `max_size`: Some(58), added: 1543, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:3 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:6 w:4)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	pub fn swap_registered_input_1_1() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1997`
		//  Estimated: `16644`
		// Minimum execution time: 8_473_709_000 picoseconds.
		Weight::from_parts(8_818_342_000, 0)
			.saturating_add(Weight::from_parts(0, 16644))
			.saturating_add(T::DbWeight::get().reads(22))
			.saturating_add(T::DbWeight::get().writes(9))
	}
	/// Storage: `EraV14Amm::Busy` (r:1 w:1)
	/// Proof: `EraV14Amm::Busy` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `Amm::Enabled` (r:1 w:0)
	/// Proof: `Amm::Enabled` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `Amm::ApprovedPairs` (r:1 w:0)
	/// Proof: `Amm::ApprovedPairs` (`max_values`: Some(1024), `max_size`: Some(26), added: 1511, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:2 w:2)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Amm::AdmittedAssets` (r:2 w:0)
	/// Proof: `Amm::AdmittedAssets` (`max_values`: Some(2048), `max_size`: Some(36), added: 1521, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Metadata` (r:2 w:0)
	/// Proof: `Assets::Metadata` (`max_values`: None, `max_size`: Some(170), added: 2645, mode: `MaxEncodedLen`)
	/// Storage: `EraV14Amm::Pools` (r:1 w:1)
	/// Proof: `EraV14Amm::Pools` (`max_values`: Some(1024), `max_size`: Some(186), added: 1671, mode: `MaxEncodedLen`)
	/// Storage: `EraV14Amm::Custodies` (r:2 w:0)
	/// Proof: `EraV14Amm::Custodies` (`max_values`: Some(1024), `max_size`: Some(58), added: 1543, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:0)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:4 w:4)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	pub fn swap_registered_output_1_0() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1894`
		//  Estimated: `11426`
		// Minimum execution time: 7_743_394_000 picoseconds.
		Weight::from_parts(8_005_655_000, 0)
			.saturating_add(Weight::from_parts(0, 11426))
			.saturating_add(T::DbWeight::get().reads(18))
			.saturating_add(T::DbWeight::get().writes(8))
	}
	/// Storage: `EraV14Amm::Busy` (r:1 w:1)
	/// Proof: `EraV14Amm::Busy` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `Amm::Enabled` (r:1 w:0)
	/// Proof: `Amm::Enabled` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `Amm::ApprovedPairs` (r:1 w:0)
	/// Proof: `Amm::ApprovedPairs` (`max_values`: Some(1024), `max_size`: Some(26), added: 1511, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:2 w:2)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Amm::AdmittedAssets` (r:2 w:0)
	/// Proof: `Amm::AdmittedAssets` (`max_values`: Some(2048), `max_size`: Some(36), added: 1521, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Metadata` (r:2 w:0)
	/// Proof: `Assets::Metadata` (`max_values`: None, `max_size`: Some(170), added: 2645, mode: `MaxEncodedLen`)
	/// Storage: `EraV14Amm::Pools` (r:1 w:1)
	/// Proof: `EraV14Amm::Pools` (`max_values`: Some(1024), `max_size`: Some(186), added: 1671, mode: `MaxEncodedLen`)
	/// Storage: `EraV14Amm::Custodies` (r:3 w:0)
	/// Proof: `EraV14Amm::Custodies` (`max_values`: Some(1024), `max_size`: Some(58), added: 1543, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:3 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:6 w:4)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	pub fn swap_registered_output_1_1() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1997`
		//  Estimated: `16644`
		// Minimum execution time: 8_633_348_000 picoseconds.
		Weight::from_parts(8_738_553_000, 0)
			.saturating_add(Weight::from_parts(0, 16644))
			.saturating_add(T::DbWeight::get().reads(22))
			.saturating_add(T::DbWeight::get().writes(9))
	}
	/// Storage: `EraV14Amm::Busy` (r:1 w:1)
	/// Proof: `EraV14Amm::Busy` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `Amm::Enabled` (r:1 w:0)
	/// Proof: `Amm::Enabled` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `Amm::ApprovedPairs` (r:1 w:0)
	/// Proof: `Amm::ApprovedPairs` (`max_values`: Some(1024), `max_size`: Some(26), added: 1511, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:1 w:1)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Amm::AdmittedAssets` (r:1 w:0)
	/// Proof: `Amm::AdmittedAssets` (`max_values`: Some(2048), `max_size`: Some(36), added: 1521, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Metadata` (r:1 w:0)
	/// Proof: `Assets::Metadata` (`max_values`: None, `max_size`: Some(170), added: 2645, mode: `MaxEncodedLen`)
	/// Storage: `EraV14Amm::Pools` (r:1 w:1)
	/// Proof: `EraV14Amm::Pools` (`max_values`: Some(1024), `max_size`: Some(186), added: 1671, mode: `MaxEncodedLen`)
	/// Storage: `EraV14Amm::Custodies` (r:2 w:0)
	/// Proof: `EraV14Amm::Custodies` (`max_values`: Some(1024), `max_size`: Some(58), added: 1543, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:2 w:2)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `EraV14Amm::Positions` (r:1 w:1)
	/// Proof: `EraV14Amm::Positions` (`max_values`: Some(1048576), `max_size`: Some(90), added: 2565, mode: `MaxEncodedLen`)
	/// Storage: `EraV14Amm::AccountPools` (r:1 w:1)
	/// Proof: `EraV14Amm::AccountPools` (`max_values`: Some(1048576), `max_size`: Some(690), added: 3165, mode: `MaxEncodedLen`)
	/// Storage: `EraV14Amm::Providers` (r:1 w:1)
	/// Proof: `EraV14Amm::Providers` (`max_values`: Some(1024), `max_size`: Some(32796), added: 34281, mode: `MaxEncodedLen`)
	pub fn add_native_new_bounded() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `40494`
		//  Estimated: `35271`
		// Minimum execution time: 6_534_335_000 picoseconds.
		Weight::from_parts(6_826_478_000, 0)
			.saturating_add(Weight::from_parts(0, 35271))
			.saturating_add(T::DbWeight::get().reads(16))
			.saturating_add(T::DbWeight::get().writes(10))
	}
	/// Storage: `EraV14Amm::Busy` (r:1 w:1)
	/// Proof: `EraV14Amm::Busy` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `Amm::Enabled` (r:1 w:0)
	/// Proof: `Amm::Enabled` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `Amm::ApprovedPairs` (r:1 w:0)
	/// Proof: `Amm::ApprovedPairs` (`max_values`: Some(1024), `max_size`: Some(26), added: 1511, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Asset` (r:2 w:2)
	/// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(210), added: 2685, mode: `MaxEncodedLen`)
	/// Storage: `Amm::AdmittedAssets` (r:2 w:0)
	/// Proof: `Amm::AdmittedAssets` (`max_values`: Some(2048), `max_size`: Some(36), added: 1521, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Metadata` (r:2 w:0)
	/// Proof: `Assets::Metadata` (`max_values`: None, `max_size`: Some(170), added: 2645, mode: `MaxEncodedLen`)
	/// Storage: `EraV14Amm::Pools` (r:1 w:1)
	/// Proof: `EraV14Amm::Pools` (`max_values`: Some(1024), `max_size`: Some(186), added: 1671, mode: `MaxEncodedLen`)
	/// Storage: `EraV14Amm::Custodies` (r:2 w:0)
	/// Proof: `EraV14Amm::Custodies` (`max_values`: Some(1024), `max_size`: Some(58), added: 1543, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:0)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Assets::Account` (r:4 w:4)
	/// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(134), added: 2609, mode: `MaxEncodedLen`)
	/// Storage: `EraV14Amm::Positions` (r:1 w:1)
	/// Proof: `EraV14Amm::Positions` (`max_values`: Some(1048576), `max_size`: Some(90), added: 2565, mode: `MaxEncodedLen`)
	/// Storage: `EraV14Amm::AccountPools` (r:1 w:1)
	/// Proof: `EraV14Amm::AccountPools` (`max_values`: Some(1048576), `max_size`: Some(690), added: 3165, mode: `MaxEncodedLen`)
	/// Storage: `EraV14Amm::Providers` (r:1 w:1)
	/// Proof: `EraV14Amm::Providers` (`max_values`: Some(1024), `max_size`: Some(32796), added: 34281, mode: `MaxEncodedLen`)
	pub fn add_registered_new_bounded() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `41650`
		//  Estimated: `35271`
		// Minimum execution time: 9_002_734_000 picoseconds.
		Weight::from_parts(9_428_460_000, 0)
			.saturating_add(Weight::from_parts(0, 35271))
			.saturating_add(T::DbWeight::get().reads(21))
			.saturating_add(T::DbWeight::get().writes(11))
	}
}
