import {installNftMetadataPanel} from './nft-metadata.mjs';
import {loadWalletProfile} from './network-profile.mjs';
import {EraWsClient} from '../sdk/era-v14-finalized-client.mjs';import {EraWalletController} from '../sdk/era-wallet-controller.mjs';import {EVALUATION_BINDINGS as bindings} from '../sdk/era-v14-evaluation.mjs';import {EraAmmClient} from '../sdk/era-v14-amm-client.mjs';import {workflows,quoteWorkflow} from './workflows.mjs';import {EraAssetsClient} from '../sdk/era-v14-assets-client.mjs';
const $=id=>document.getElementById(id),show=v=>JSON.stringify(v,(_,x)=>typeof x==='bigint'?x.toString():x,2);let wallet,rpc,preview,busy=false;
let profile;try{profile=await loadWalletProfile();$('network').textContent=profile.label+' · ETKN · 18 decimals';$('deployment-note').textContent=profile.network==='development'?'Disposable-chain profile. Production commissioning remains pending.':'Reviewed production profile. Connection requires the exact approved runtime and metadata; publication of this application requires separate deployment approval.';}catch(error){$('status').textContent=error.message;throw error;}
const genesis=profile.genesisHash;
function option(select,value,label){const o=document.createElement('option');o.value=value;o.textContent=label;select.append(o);}
function invalidate(){$('sign').disabled=true;preview=undefined;$('preview-text').textContent='';}
function discover(){$('provider').replaceChildren();for(const name of Object.keys(globalThis.injectedWeb3??{}))option($('provider'),name,name);}
function fields(){invalidate();$('fields').replaceChildren();for(const f of workflows[Number($('workflow').value)].fields){const label=document.createElement('label');label.textContent=f.label;const input=document.createElement('input');input.name=f.key;input.value=f.value;input.autocomplete='off';input.required=!/blank|Optional/i.test(f.label);input.addEventListener('input',invalidate);label.append(input);$('fields').append(label);}}
function controls(){for(const button of document.querySelectorAll('button'))button.disabled=(busy&&button.id!=='disconnect')||button.dataset.unavailable==='true';$('sign').disabled=busy||!preview;$('preview').disabled=busy||!wallet?.accounts?.length;for(const input of document.querySelectorAll('#fields input,#account,#workflow'))input.disabled=busy;}
async function action(fn){if(busy)return;busy=true;controls();try{$('status').textContent='Working…';const result=await fn();$('status').textContent=typeof result==='string'?result:show(result);}catch(e){$('status').textContent=e.message;invalidate();}finally{busy=false;controls();}}
for(const [i,w] of workflows.entries())option($('workflow'),String(i),w.label);fields();discover();
$('discover').onclick=discover;$('workflow').onchange=fields;$('fields').onsubmit=e=>e.preventDefault();$('account').onchange=invalidate;
$('connect').onclick=()=>action(async()=>{wallet?.disconnect();rpc?.close();rpc=new EraWsClient(profile.rpc);const response=await fetch('../fixtures/development-event-schema.json');if(!response.ok)throw new Error('reviewed schema unavailable');const schema=await response.json();wallet=new EraWalletController({rpc,bindings,schema,expectedGenesisHash:genesis,source:$('provider').value,applicationName:profile.label});const accounts=await wallet.connect();$('account').replaceChildren();for(const account of accounts)option($('account'),account.address,(account.name??'Account')+' · '+account.address);invalidate();return {network:'Verified '+profile.label,pending:wallet.pending(),accounts:accounts.length};});
$('disconnect').onclick=()=>{wallet?.disconnect();rpc?.close();wallet=undefined;$('account').replaceChildren();invalidate();$('status').textContent='Disconnected. Any submitted pending transaction remains stored for reconciliation.';};
$('balance').onclick=()=>action(async()=>{if(!wallet)throw new Error('Connect first');const b=await wallet.balance($('account').value);$('funds').textContent=`${b.freeEtkn} ETKN free · ${b.reservedEtkn} ETKN reserved`;return b;});
$('preview').onclick=()=>action(async()=>{if(!wallet)throw new Error('Connect first');const inputs=[...$('fields').querySelectorAll('input')];if(inputs.some(x=>x.required&&!x.value))throw new Error('Complete the required action fields');const workflow=workflows[Number($('workflow').value)],values=Object.fromEntries(inputs.map(x=>[x.name,x.value]));preview=await wallet.prepare($('account').value,workflow.encode(values));$('preview-text').textContent=show({action:workflow.label,values,account:preview.address,estimatedFeeEtkn:preview.feeEtkn,nonce:preview.nonce,expiresAtBlock:preview.death});$('sign').disabled=false;return 'Review the action, amount and fee above. Signing happens only after you press Review and sign in wallet.';});
$('sign').onclick=()=>action(async()=>{if(!wallet||!preview)throw new Error('Prepare a fresh preview');const selected=preview;invalidate();return await wallet.signAndSubmit(selected);});
$('reconcile').onclick=()=>action(async()=>{if(!wallet)throw new Error('Connect first');return wallet.reconcile();});
$('pools').onclick=()=>action(async()=>{if(!wallet)throw new Error('Connect first');const amm=new EraAmmClient(wallet);const results={pools:await amm.pools(),positions:await amm.positions($('account').value)};$('pools-text').textContent=show(results);return 'Read from finalized blocks; LP balances are internal accounting units.';});

$('metadata').onclick=()=>action(async()=>{if(!wallet)throw new Error('Connect first');return wallet.provideMetadata(profile.label);});

$('quote').onclick=()=>action(async()=>{if(!wallet)throw new Error('Connect first');const values=Object.fromEntries([...$('fields').querySelectorAll('input')].map(x=>[x.name,x.value]));const r=await quoteWorkflow(new EraAmmClient(wallet),Number($('workflow').value),values,$('slippage').value);invalidate();$('fields').querySelector(`[name=${r.field}]`).value=r.bound;$('fields').querySelector('[name=deadline]').value=r.deadline;$('quote-text').textContent=show(r);return 'Finalized quote applied. Review the bound and prepare a fresh fee preview; execution price can change.';});
$('asset-info').onclick=()=>action(async()=>{if(!wallet)throw new Error('Connect first');const data=await new EraAssetsClient(wallet).asset($('asset-id').value);const text=hex=>{try{return new TextDecoder('utf-8',{fatal:true}).decode(Uint8Array.from(hex.slice(2).match(/../g)??[],b=>parseInt(b,16)));}catch{return '(non-UTF8; exact bytes retained below)';}};const m=data.value.metadata;const display={...data,...(m?{name:text(m.nameHex),symbol:text(m.symbolHex)}:{})};$('asset-text').textContent=show(display);return 'Metadata is read at a verified finalized block. Quantities in action forms are explicitly labelled base units.';});

await installNftMetadataPanel({document,network:profile.network,getWallet:()=>wallet,action});
